In [2]:
import itertools
import pandas as pd
import sqlalchemy as sqa
import numpy as np
from tensorflow.keras import models, layers
from tensorflow.keras.layers import Input

DB = f'postgres://localhost/{"poker"}'
ENGINE = sqa.create_engine(DB)

max_features = 53
max_len = 7
vector_size = 4

In [3]:
df = pd.read_sql_table("results", con=ENGINE)

In [4]:
y = np.array(df['action'])

In [5]:
cards = np.array(df[['hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']].loc[0])
for i in range(1, df.shape[0]):
    cards = np.vstack((cards, np.array(df[['hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']].loc[i])))
cards

array([[33., 15.,  0., ...,  0.,  0.,  0.],
       [20., 47.,  0., ...,  0.,  0.,  0.],
       [22.,  4.,  0., ...,  0.,  0.,  0.],
       ...,
       [27., 15., 17., ..., 22.,  1.,  0.],
       [ 8., 47., 17., ..., 22.,  1.,  0.],
       [27., 15., 17., ..., 22.,  1.,  0.]])

In [6]:
cards.shape

(201, 7)

In [16]:
cards[0]

array([33., 15.,  0.,  0.,  0.,  0.,  0.])

In [7]:
rest = np.array(df[['position', 'round', 'active_0', 'active_1', 'active_2', 'active_3', 'active_4', 'bid', 'bid_0', 'bid_1', 'bid_2', 'bid_3', 'bid_4']].loc[0])
for i in range(1, df.shape[0]):
    rest = np.vstack((rest, np.array(df[['position', 'round', 'active_0', 'active_1', 'active_2', 'active_3', 'active_4', 'bid', 'bid_0', 'bid_1', 'bid_2', 'bid_3', 'bid_4']].loc[i])))
rest

array([[2.0e+00, 1.0e+00, 1.0e+00, ..., 0.0e+00, 0.0e+00, 0.0e+00],
       [3.0e+00, 1.0e+00, 1.0e+00, ..., 0.0e+00, 0.0e+00, 0.0e+00],
       [4.0e+00, 1.0e+00, 1.0e+00, ..., 0.0e+00, 0.0e+00, 0.0e+00],
       ...,
       [2.0e+00, 3.0e+00, 1.0e+00, ..., 4.0e+02, 8.0e+02, 1.8e+03],
       [0.0e+00, 3.0e+00, 0.0e+00, ..., 4.0e+02, 8.0e+02, 1.8e+03],
       [2.0e+00, 3.0e+00, 1.0e+00, ..., 4.0e+02, 8.0e+02, 1.8e+03]])

In [8]:
rest.shape

(201, 13)

Create a model:

In [9]:
# Card embeddings
card_input = Input(shape=cards.shape[1])
card_output = layers.Embedding(max_features, vector_size, input_length=max_len)(card_input)
card_output = layers.Flatten()(card_output)

# Other information
state_input = Input(shape=rest.shape[1])

#Merge and add dense layer
merge_layer = layers.concatenate([state_input, card_output])
x = layers.Dense(64, activation='relu')(merge_layer)
x = layers.Dense(32, activation='relu')(x)
main_output = layers.Dense(3, activation='softmax')(x)

# Define model with two inputs
model = models.Model(inputs=[card_input, state_input], outputs=[main_output])

model.compile(
    optimizer='rmsprop',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

W0810 18:12:26.426512 4744574400 deprecation.py:506] From /Users/stefanroth/anaconda3/envs/poker/lib/python3.7/site-packages/tensorflow/python/keras/initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0810 18:12:26.462013 4744574400 deprecation.py:506] From /Users/stefanroth/anaconda3/envs/poker/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [26]:
model.fit([cards, rest], y, batch_size=10, epochs=10)

Epoch 1/10
201/201 [==============================] - 0s 223us/sample - loss: 14.8911 - acc: 0.5224
Epoch 2/10
201/201 [==============================] - 0s 230us/sample - loss: 11.9024 - acc: 0.5622
Epoch 3/10
201/201 [==============================] - 0s 178us/sample - loss: 13.8787 - acc: 0.5373
Epoch 4/10
201/201 [==============================] - 0s 193us/sample - loss: 9.2593 - acc: 0.6070
Epoch 5/10
201/201 [==============================] - 0s 198us/sample - loss: 9.2232 - acc: 0.6617
Epoch 6/10
201/201 [==============================] - 0s 206us/sample - loss: 9.7201 - acc: 0.6119
Epoch 7/10
201/201 [==============================] - 0s 218us/sample - loss: 10.1314 - acc: 0.6070
Epoch 8/10
201/201 [==============================] - 0s 236us/sample - loss: 8.6636 - acc: 0.6119
Epoch 9/10
201/201 [==============================] - 0s 214us/sample - loss: 11.0821 - acc: 0.5622
Epoch 10/10
201/201 [==============================] - 0s 197us/sample - loss: 8.8118 - acc: 0.6468


In [24]:
cards[0].shape

(7,)

In [22]:
[cards[0], rest[0]]

[array([33., 15.,  0.,  0.,  0.,  0.,  0.]),
 array([  2.,   1.,   1.,   1.,   1.,   1.,   1.,   0., 100., 200.,   0.,
          0.,   0.])]

In [28]:
model.predict([cards[0:9], rest[0:9]])

array([[1.00000000e+00, 9.47840286e-15, 2.83321147e-18],
       [1.00000000e+00, 1.03631957e-14, 2.18358104e-18],
       [1.00000000e+00, 9.78454090e-15, 1.50575802e-18],
       [1.00000000e+00, 8.91378680e-15, 8.97898661e-19],
       [1.00000000e+00, 2.11110729e-09, 4.43053016e-12],
       [2.08673324e-22, 1.03473174e-10, 1.00000000e+00],
       [2.42386333e-10, 6.01358414e-02, 9.39864159e-01],
       [9.20188725e-08, 9.99998927e-01, 9.51850552e-07],
       [6.32742058e-06, 9.99993682e-01, 2.83651547e-09]], dtype=float32)

In [ ]:
from keras.layers import Merge

left_branch = Sequential()
left_branch.add(layers.Embedding(max_features, vector_size, input_length=max_len))

right_branch = Sequential()
right_branch.add(Dense(32, input_dim=784))

merged = Merge([left_branch, right_branch], mode='concat')

final_model = Sequential()
final_model.add(merged)
final_model.add(Dense(10, activation='softmax'))

In [24]:
model = models.Sequential()

model.add(layers.Embedding(
    max_features, vector_size, input_length=max_len
    # Number of distinct features, size of the word vector, input size
                          ))
state_input = Input(shape=rest.shape)

model.add(layers.Flatten())
model.add(layers.Dense(1, activation='softmax'))
model.summary()

model.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

W0810 17:43:26.784821 4741285312 deprecation.py:506] From /Users/stefanroth/anaconda3/envs/poker/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 7, 4)              212       
_________________________________________________________________
flatten (Flatten)            (None, 28)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 29        
Total params: 241
Trainable params: 241
Non-trainable params: 0
_________________________________________________________________


In [103]:
df.columns

Index(['index', 'action', 'active_0', 'active_1', 'active_2', 'active_3',
       'active_4', 'bid', 'bid_0', 'bid_1', 'bid_2', 'bid_3', 'bid_4',
       'community1', 'community2', 'community3', 'community4', 'community5',
       'hand1', 'hand2', 'player', 'position', 'round', 'reward'],
      dtype='object')

In [10]:
rest = df[['position', 'round', 'active_0', 'active_1', 'active_2', 'active_3', 'active_4', 'bid', 'bid_0', 'bid_1', 'bid_2', 'bid_3', 'bid_4'\
          , 'hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']]

In [14]:
df.head()

index  action  active_0  active_1  active_2  active_3  active_4    bid  \
0      0     4.0       1.0       1.0       1.0       1.0       1.0  200.0   
1      1     0.0       1.0       1.0       1.0       1.0       1.0    0.0   
2      2     4.0       1.0       1.0       1.0       0.0       1.0  200.0   
3      3     5.0       1.0       1.0       1.0       0.0       1.0  400.0   
4      4     4.0       1.0       1.0       0.0       1.0       1.0  400.0   

   bid_0  bid_1  ...  community2  community3  community4  community5  hand1  \
0  100.0  200.0  ...       999.0       999.0       999.0       999.0   25.0   
1  100.0  200.0  ...       999.0       999.0       999.0       999.0   44.0   
2  100.0  200.0  ...       999.0       999.0       999.0       999.0   31.0   
3  100.0  200.0  ...       999.0       999.0       999.0       999.0   11.0   
4  200.0  200.0  ...       999.0       999.0       999.0       999.0    0.0   

   hand2  player  position  round  reward  
0   22.0     2.0       2.0    1.0  -400.0  
1   51.0     3.0       3.0    1.0     0.0  
2   35.0     4.0       4.0    1.0 -1000.0  
3   42.0     5.0       5.0    1.0 -1600.0  
4    8.0     0.0       0.0    1.0 -2000.0  

[5 rows x 24 columns]

In [86]:
class Agent:
    '''
    The class Agent takes the following parameters as input:
    
    and uses them to decide on his action in a specified game of poker
    '''
    
    def __init__(self, df):
        self.dataframe = df
        self.input_card_embedding = ""
        self.input_state = ""
        self.rewards = df[['action', 'reward']]
    
    def create_embedding_input(self):
        '''
        The function create_embedding_input creates the input for the embedding of the card vectors
        '''
        cards = np.array(self.dataframe[['hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']].loc[0])
        for i in range(1, df.shape[0]):
            cards = np.vstack((cards, np.array(self.dataframe[['hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']].loc[i])))
        
        self.input_card_embedding = cards
        
    
    def create_state_input(self):
        '''
        The function create_state_input creates the input for the neural network apart from the card embeddings
        '''
        state = np.array(df[['position', 'round', 'active_0', 'active_1', 'active_2', 'active_3', 'active_4', 'bid', 'bid_0', 'bid_1', 'bid_2', 'bid_3', 'bid_4'\
          , 'hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']].loc[0])
        for i in range(1, df.shape[0]):
            state = np.vstack((rest, np.array(df[['position', 'round', 'active_0', 'active_1', 'active_2', 'active_3', 'active_4', 'bid', 'bid_0', 'bid_1', 'bid_2', 'bid_3', 'bid_4'\
                  , 'hand1', 'hand2', 'community1', 'community2', 'community3', 'community4', 'community5']].loc[i])))
        
        self.input_state = rest
        

In [87]:
agent = Agent(df)

In [88]:
agent.create_embedding_input()

In [89]:
agent.input_card_embedding

array([[ 25.,  22., 999., ..., 999., 999., 999.],
       [ 44.,  51., 999., ..., 999., 999., 999.],
       [ 31.,  35., 999., ..., 999., 999., 999.],
       ...,
       [ 49.,  34., 999., ..., 999., 999., 999.],
       [ 31.,  46., 999., ..., 999., 999., 999.],
       [  8.,   1., 999., ..., 999., 999., 999.]])

In [4]:
df.hand1[0], df.hand2[1]

(25.0, 51.0)

Let us look at the community cards:

In [8]:
for i in range(df.shape[0]):
    if len(df.community[i]) > 2:
        print(df.community[i])

{"(q,c)","(5,d)","(7,c)"}
{"(q,c)","(5,d)","(7,c)"}
{"(q,c)","(5,d)","(7,c)","(j,d)"}
{"(q,c)","(5,d)","(7,c)","(j,d)"}
{"(q,c)","(5,d)","(7,c)","(j,d)"}
{"(3,d)","(t,h)","(a,c)"}
{"(3,d)","(t,h)","(a,c)"}
{"(3,d)","(t,h)","(a,c)","(q,c)"}
{"(3,d)","(t,h)","(a,c)","(q,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)"}
{"(3,h)","(7,s)","(9,c)","(k,d)"}
{"(3,h)","(7,s)","(9,c)","(k,d)"}
{"(3,h)","(7,s)","(9,c)","(k,d)"}
{"(3,h)","(7,s)","(9,c)","(k,d)"}
{"(3,h)","(7,s)","(9,c)","(k,d)"}
{"(3,h)","(2,c)","(4,h)"}
{"(3,h)","(2,c)","(4,h)"}
{"(3,h)","(2,c)","(4,h)","(a,c)"}
{"(3,h)","(2,c)","(4,h)","(a,c)"}
{"(k,d)","(2,c)","(5,d)"}
{"(k,d)","(2,c)","(5